version: "3.8"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    hostname: transmission
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Ho_Chi_Minh
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=torrent
      - PASS=torrent
    volumes:
      - transmission:/config
      - data:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

volumes:
  transmission:
    external: true
  data:
    external: true
